name: Build & Push Docker Image

on:
  push:
    branches: [main]
    paths:
      - 'check_cpu.py'
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t zhen06199/pricing-service:latest .

      - name: Push Docker image
        run: docker push zhen06199/pricing-service:latest
